### ISSUE TITLE
Included 'from_local_file' pipeline is outdated

### ISSUE THREAD

**Issue by makkus** [DHARPA-Project/kiara_plugin.network_analysis#3]
**Describe the bug**

The included 'from_local_file' pipeline is outdated, as it still includes the 'file.import_from..' operation ids. Either this must be removed, or updated. Import modules/operations are on hold until we've decided on an overall, good, generic strategy on how to deal with this.

**To Reproduce**
```
kiara pipeline explain network_graph.import.from_local_files
Traceback (most recent call last):
  File "/home/markus/projects/dharpa/kiara/src/kiara/pipeline/structure.py", line 120, in module
    self._module = self.kiara.create_module(
  File "/home/markus/projects/dharpa/kiara/src/kiara/kiara.py", line 361, in create_module
    return self._module_mgr.create_module(
  File "/home/markus/projects/dharpa/kiara/src/kiara/module_mgmt/merged.py", line 248, in create_module
    raise Exception(
```

**Expected behavior**
For it to not to be available, or not throwing an error.

**Comment by makkus** [comment]
Should be fixed.
